language: go

go:
  - "1.12.x"

install:
  - go get github.com/op/go-logging
  - go get github.com/json-iterator/go
  - go get go.uber.org/zap
  - go get github.com/dgrijalva/jwt-go
  - go get github.com/jinzhu/gorm
  - github.com/go-sql-driver/mysql
  - github.com/go-redis/redis
  - github.com/gomodule/redigo/redis

scirpt:
  - go test  -cover ./...